-- KÒR System Data Import (without feature_flags enabled_for_users/disabled_countries)

-- ===============================
-- COUNTRIES (10 rows)
-- ===============================
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Bénin', 'BJ', '+229', 'XOF', false) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Burkina Faso', 'BF', '+226', 'XOF', false) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Cameroun', 'CM', '+237', 'XAF', false) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Côte d''Ivoire', 'CI', '+225', 'XOF', true) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Gabon', 'GA', '+241', 'XAF', false) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Guinée', 'GN', '+224', 'GNF', false) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Mali', 'ML', '+223', 'XOF', false) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Niger', 'NE', '+227', 'XOF', false) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Sénégal', 'SN', '+221', 'XOF', true) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;
INSERT INTO countries (name, code, phone_prefix, currency, is_active) VALUES ('Togo', 'TG', '+228', 'XOF', true) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, phone_prefix = EXCLUDED.phone_prefix, currency = EXCLUDED.currency, is_active = EXCLUDED.is_active;

-- ===============================
-- SUBSCRIPTION PLANS (4 rows)
-- ===============================
INSERT INTO subscription_plans (name, price, duration_days, currency, features, is_active, sort_order, description, max_clients, max_sales_per_day, commission_reduction) VALUES ('Gratuit', 0, 7, 'XOF', '["basic_sales","basic_stock","basic_clients","basic_debts","alerts","clients","debts","multi_currency","reports","sales","stock","network","invoices","offline_mode","employees","referrals","ai_analysis","voice_input","commission_payment"]'::jsonb, true, 0, 'Essai gratuit de 7 jours', 5, 5, NULL) ON CONFLICT (name) DO UPDATE SET price = EXCLUDED.price, duration_days = EXCLUDED.duration_days, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, description = EXCLUDED.description, max_clients = EXCLUDED.max_clients, max_sales_per_day = EXCLUDED.max_sales_per_day;
INSERT INTO subscription_plans (name, price, duration_days, currency, features, is_active, sort_order, description, max_clients, max_sales_per_day, commission_reduction) VALUES ('Starter', 1500, 30, 'XOF', '["basic_sales","basic_stock","basic_clients","basic_debts","referrals","clients","reports","sales","offline_mode","commission_payment","multi_currency","stock","debts","alerts","invoices","ai_analysis","voice_input"]'::jsonb, true, 1, 'Pour les petites boutiques', 10, 10, NULL) ON CONFLICT (name) DO UPDATE SET price = EXCLUDED.price, duration_days = EXCLUDED.duration_days, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, description = EXCLUDED.description, max_clients = EXCLUDED.max_clients, max_sales_per_day = EXCLUDED.max_sales_per_day;
INSERT INTO subscription_plans (name, price, duration_days, currency, features, is_active, sort_order, description, max_clients, max_sales_per_day, commission_reduction) VALUES ('Premium', 5000, 30, 'XOF', '["basic_sales","basic_stock","basic_clients","basic_debts","reports","voice_input","network","ai_analysis","employees","alerts","debts","clients","stock","sales","offline_mode","referrals","invoices","commission_payment","multi_currency"]'::jsonb, true, 2, 'Fonctionnalités avancées', NULL, NULL, NULL) ON CONFLICT (name) DO UPDATE SET price = EXCLUDED.price, duration_days = EXCLUDED.duration_days, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, description = EXCLUDED.description, max_clients = EXCLUDED.max_clients, max_sales_per_day = EXCLUDED.max_sales_per_day;
INSERT INTO subscription_plans (name, price, duration_days, currency, features, is_active, sort_order, description, max_clients, max_sales_per_day, commission_reduction) VALUES ('Annuel Premium', 50000, 365, 'XOF', '["basic_sales","basic_stock","basic_clients","basic_debts","reports","voice_input","network","ai_analysis","employees","priority_support"]'::jsonb, true, 3, 'Premium avec 2 mois offerts', NULL, NULL, NULL) ON CONFLICT (name) DO UPDATE SET price = EXCLUDED.price, duration_days = EXCLUDED.duration_days, features = EXCLUDED.features, is_active = EXCLUDED.is_active, sort_order = EXCLUDED.sort_order, description = EXCLUDED.description, max_clients = EXCLUDED.max_clients, max_sales_per_day = EXCLUDED.max_sales_per_day;

-- ===============================
-- FEATURE FLAGS (15 rows) - without enabled_for_users which is uuid[]
-- ===============================
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('sales', 'Ventes', 'Enregistrement et suivi des ventes', true, NULL, ARRAY[]::text[], 'primary', 0, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('stock', 'Stock', 'Gestion du stock et inventaire', true, NULL, ARRAY[]::text[], 'primary', 1, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('clients', 'Clients', 'Gestion de la base clients', true, NULL, ARRAY[]::text[], 'primary', 2, false, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('debts', 'Créances', 'Suivi des dettes clients', true, NULL, ARRAY['clients']::text[], 'primary', 3, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('offline_mode', 'Mode Hors Ligne', 'Synchronisation des données en mode offline', true, NULL, ARRAY[]::text[], 'primary', 4, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('reports', 'Rapports', 'Rapports et statistiques avancés', true, 'starter', ARRAY['sales']::text[], 'secondary', 0, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('voice_input', 'Entrée vocale', 'Saisie vocale des ventes et stock', true, 'starter', ARRAY[]::text[], 'secondary', 1, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('alerts', 'Alertes', 'Rappels automatiques pour dettes et expiration', true, 'starter', ARRAY[]::text[], 'secondary', 2, false, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('ai_analysis', 'Analyse IA', 'Analyse intelligente des données', true, 'premium', ARRAY['voice_input']::text[], 'secondary', 3, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('network', 'Réseau Marchands', 'Réseau B2B entre marchands', false, 'premium', ARRAY['clients']::text[], 'secondary', 4, false, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('employees', 'Gestion Employés', 'Gestion des employés et permissions', true, 'premium', ARRAY[]::text[], 'secondary', 5, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('referrals', 'Parrainage', 'Système de parrainage et commissions affiliés', true, NULL, ARRAY[]::text[], 'secondary', 6, false, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('invoices', 'Factures', 'Génération de factures PDF professionnelles', true, 'starter', ARRAY['sales']::text[], 'secondary', 7, true, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('multi_currency', 'Multi-devises', 'Support de plusieurs devises', true, 'starter', ARRAY[]::text[], 'secondary', 8, false, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;
INSERT INTO feature_flags (feature_key, name, description, is_globally_enabled, min_plan_required, depends_on, category, sort_order, is_beta, current_version) VALUES ('commission_payment', 'Paiement Commission', 'Gestion des paiements de commissions', true, 'starter', ARRAY[]::text[], 'secondary', 9, false, '1.0.0') ON CONFLICT (feature_key) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, is_globally_enabled = EXCLUDED.is_globally_enabled, min_plan_required = EXCLUDED.min_plan_required, depends_on = EXCLUDED.depends_on, category = EXCLUDED.category, is_beta = EXCLUDED.is_beta;

-- ===============================
-- ROADMAP ITEMS (8 rows)
-- ===============================
INSERT INTO roadmap_items (title, description, category, status, priority, target_version, estimated_effort) VALUES ('Mode hors ligne', 'Actuellement, lorsqu''on fait une operation, ca refuse.', 'improvement', 'completed', 'urgent', NULL, NULL) ON CONFLICT (title) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, status = EXCLUDED.status, priority = EXCLUDED.priority;
INSERT INTO roadmap_items (title, description, category, status, priority, target_version, estimated_effort) VALUES ('Confusion Commission', 'Les deux sont confondu et liés.', 'bug', 'completed', 'urgent', NULL, NULL) ON CONFLICT (title) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, status = EXCLUDED.status, priority = EXCLUDED.priority;
INSERT INTO roadmap_items (title, description, category, status, priority, target_version, estimated_effort) VALUES ('Transcription offline', 'Prévoir API browser de transcription.', 'performance', 'completed', 'urgent', NULL, NULL) ON CONFLICT (title) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, status = EXCLUDED.status, priority = EXCLUDED.priority;
INSERT INTO roadmap_items (title, description, category, status, priority, target_version, estimated_effort) VALUES ('Gestion stock', 'Le menu lui est visible mais que doit-on afficher.', 'improvement', 'completed', 'high', NULL, NULL) ON CONFLICT (title) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, status = EXCLUDED.status, priority = EXCLUDED.priority;
INSERT INTO roadmap_items (title, description, category, status, priority, target_version, estimated_effort) VALUES ('Amelioration Note vocal', 'Permettre un apprentissage.', 'bug', 'completed', 'urgent', NULL, NULL) ON CONFLICT (title) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, status = EXCLUDED.status, priority = EXCLUDED.priority;
INSERT INTO roadmap_items (title, description, category, status, priority, target_version, estimated_effort) VALUES ('Bugs Activation', 'Checker toutes les features côté admin.', 'bug', 'completed', 'urgent', NULL, NULL) ON CONFLICT (title) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, status = EXCLUDED.status, priority = EXCLUDED.priority;
INSERT INTO roadmap_items (title, description, category, status, priority, target_version, estimated_effort) VALUES ('Revoir Onboarding', 'Les infos que l''utilisateur inscrit.', 'bug', 'completed', 'urgent', NULL, NULL) ON CONFLICT (title) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, status = EXCLUDED.status, priority = EXCLUDED.priority;
INSERT INTO roadmap_items (title, description, category, status, priority, target_version, estimated_effort) VALUES ('Amelioration UI settings', 'Ranger mieux, garder abonnement visible en haut.', 'improvement', 'in_progress', 'high', NULL, NULL) ON CONFLICT (title) DO UPDATE SET description = EXCLUDED.description, category = EXCLUDED.category, status = EXCLUDED.status, priority = EXCLUDED.priority;

-- ===============================
-- COMMISSIONS (1 row)
-- ===============================
INSERT INTO commissions (name, type, value, applies_to, is_active, country_id) VALUES ('Générale Commission', 'percentage', 2, 'all_sales', true, NULL) ON CONFLICT (name) DO UPDATE SET type = EXCLUDED.type, value = EXCLUDED.value, applies_to = EXCLUDED.applies_to, is_active = EXCLUDED.is_active;

-- ===============================
-- RESELLERS (1 row)
-- ===============================
INSERT INTO resellers (id, name, email, phone, city, commission_rate, is_active, total_codes_sold, total_earnings, user_id) VALUES ('7526d5e1-7822-4028-9c55-00a4ad379d77', 'Pascal', 'pascal@kor.local', '+22892509659', 'Lomé', 10, true, 0, 0, NULL) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, commission_rate = EXCLUDED.commission_rate, is_active = EXCLUDED.is_active;

-- ===============================
-- ENSURE CURRENT USER HAS ADMIN ROLE + PREMIUM
-- ===============================
INSERT INTO user_roles (user_id, role) 
VALUES ('13956afb-4fea-4c46-870a-5ee08c0308a7', 'admin') 
ON CONFLICT (user_id, role) DO NOTHING;

UPDATE subscriptions 
SET plan = 'premium', 
    is_active = true, 
    trial_ends_at = NOW() + INTERVAL '30 days',
    max_clients = NULL,
    max_sales_per_day = NULL
WHERE user_id = '13956afb-4fea-4c46-870a-5ee08c0308a7';